In [2]:
import pandas as pd

df = pd.read_csv('../data/Library_Usage_Small.csv',
                 low_memory=False
                )
df.to_json('../data/Library_Usage_Small.json')
df = pd.read_json('../data/Library_Usage_Small.json')
df

,Unnamed: 0,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,123022,2,Teen,0,0,10 to 19 years,x,Main,Oct,2022.0,z,Email,True,2022,False
1,125054,0,Adult,0,0,25 to 34 years,x,Main,Jul,2023.0,z,Email,True,2021,False
2,87884,0,Adult,0,0,25 to 34 years,x,Main,None,NaN,z,Email,True,2023,False
3,409236,0,Adult,19,40,20 to 24 years,p9,Presidio,Jul,2023.0,z,Email,True,2021,False
4,47911,3,Senior,1079,197,75 years and over,x,Main,Jul,2023.0,z,Email,True,2003,False
5,393489,0,Adult,10,5,45 to 54 years,x,Main,Jul,2023.0,None,None,False,2003,False
6,5884,0,Adult,0,0,25 to 34 years,x,Main,Mar,2020.0,z,Email,True,2020,False
7,329892,2,Teen,137,0,10 to 19 years,yb,Bookmobile,Feb,2021.0,z,Email,True,2009,False
8,49195,1,Juvenile,0,0,10 to 19 years,x,Main,Apr,2020.0,z,Email,True,2017,False
9,298115,1,Juvenile,6,23,0 to 9 years,m2,Marina,May,2023.0,z,Email,True,2021,False

In [3]:
df.to_html('../data/Library_Usage_Small.html', index=False)
df = pd.read_html('../data/Library_Usage_Small.html')
df = df[0]
df

,Unnamed: 0,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,123022,2,Teen,0,0,10 to 19 years,x,Main,Oct,2022.0,z,Email,True,2022,False
1,125054,0,Adult,0,0,25 to 34 years,x,Main,Jul,2023.0,z,Email,True,2021,False
2,87884,0,Adult,0,0,25 to 34 years,x,Main,None,NaN,z,Email,True,2023,False
3,409236,0,Adult,19,40,20 to 24 years,p9,Presidio,Jul,2023.0,z,Email,True,2021,False
4,47911,3,Senior,1079,197,75 years and over,x,Main,Jul,2023.0,z,Email,True,2003,False
5,393489,0,Adult,10,5,45 to 54 years,x,Main,Jul,2023.0,None,None,False,2003,False
6,5884,0,Adult,0,0,25 to 34 years,x,Main,Mar,2020.0,z,Email,True,2020,False
7,329892,2,Teen,137,0,10 to 19 years,yb,Bookmobile,Feb,2021.0,z,Email,True,2009,False
8,49195,1,Juvenile,0,0,10 to 19 years,x,Main,Apr,2020.0,z,Email,True,2017,False
9,298115,1,Juvenile,6,23,0 to 9 years,m2,Marina,May,2023.0,z,Email,True,2021,False

In [4]:
df.to_excel('../data/Library_Usage_Small.xlsx', index=False)
df = pd.read_excel('../data/Library_Usage_Small.xlsx')
df

,Unnamed: 0,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,123022,2,Teen,0,0,10 to 19 years,x,Main,Oct,2022.0,z,Email,True,2022,False
1,125054,0,Adult,0,0,25 to 34 years,x,Main,Jul,2023.0,z,Email,True,2021,False
2,87884,0,Adult,0,0,25 to 34 years,x,Main,None,NaN,z,Email,True,2023,False
3,409236,0,Adult,19,40,20 to 24 years,p9,Presidio,Jul,2023.0,z,Email,True,2021,False
4,47911,3,Senior,1079,197,75 years and over,x,Main,Jul,2023.0,z,Email,True,2003,False
5,393489,0,Adult,10,5,45 to 54 years,x,Main,Jul,2023.0,None,None,False,2003,False
6,5884,0,Adult,0,0,25 to 34 years,x,Main,Mar,2020.0,z,Email,True,2020,False
7,329892,2,Teen,137,0,10 to 19 years,yb,Bookmobile,Feb,2021.0,z,Email,True,2009,False
8,49195,1,Juvenile,0,0,10 to 19 years,x,Main,Apr,2020.0,z,Email,True,2017,False
9,298115,1,Juvenile,6,23,0 to 9 years,m2,Marina,May,2023.0,z,Email,True,2021,False

In [5]:
df.to_csv('../data/Library_Usage_Small_Copy.csv')
#df.to_csv('../data/Library_Usage_Small_Copy.csv', index=False) 
#Vergleiche die resultierenden Dateien!